export const flags = [
  {
    code: "AC",
    unicode: "U+1F1E6 U+1F1E8",
    name: "Ascension Island",
    flag: "🇦🇨",
  },
  {
    code: "AD",
    unicode: "U+1F1E6 U+1F1E9",
    name: "Andorra",
    flag: "🇦🇩",
  },
  {
    code: "AE",
    unicode: "U+1F1E6 U+1F1EA",
    name: "United Arab Emirates",
    flag: "🇦🇪",
  },
  {
    code: "AF",
    unicode: "U+1F1E6 U+1F1EB",
    name: "Afghanistan",
    flag: "🇦🇫",
  },
  {
    code: "AG",
    unicode: "U+1F1E6 U+1F1EC",
    name: "Antigua & Barbuda",
    flag: "🇦🇬",
  },
  {
    code: "AI",
    unicode: "U+1F1E6 U+1F1EE",
    name: "Anguilla",
    flag: "🇦🇮",
  },
  {
    code: "AL",
    unicode: "U+1F1E6 U+1F1F1",
    name: "Albania",
    flag: "🇦🇱",
  },
  {
    code: "AM",
    unicode: "U+1F1E6 U+1F1F2",
    name: "Armenia",
    flag: "🇦🇲",
  },
  {
    code: "AO",
    unicode: "U+1F1E6 U+1F1F4",
    name: "Angola",
    flag: "🇦🇴",
  },
  {
    code: "AQ",
    unicode: "U+1F1E6 U+1F1F6",
    name: "Antarctica",
    flag: "🇦🇶",
  },
  {
    code: "AR",
    unicode: "U+1F1E6 U+1F1F7",
    name: "Argentina",
    flag: "🇦🇷",
  },
  {
    code: "AS",
    unicode: "U+1F1E6 U+1F1F8",
    name: "American Samoa",
    flag: "🇦🇸",
  },
  {
    code: "AT",
    unicode: "U+1F1E6 U+1F1F9",
    name: "Austria",
    flag: "🇦🇹",
  },
  {
    code: "AU",
    unicode: "U+1F1E6 U+1F1FA",
    name: "Australia",
    flag: "🇦🇺",
  },
  {
    code: "AW",
    unicode: "U+1F1E6 U+1F1FC",
    name: "Aruba",
    flag: "🇦🇼",
  },
  {
    code: "AX",
    unicode: "U+1F1E6 U+1F1FD",
    name: "Åland Islands",
    flag: "🇦🇽",
  },
  {
    code: "AZ",
    unicode: "U+1F1E6 U+1F1FF",
    name: "Azerbaijan",
    flag: "🇦🇿",
  },
  {
    code: "BA",
    unicode: "U+1F1E7 U+1F1E6",
    name: "Bosnia & Herzegovina",
    flag: "🇧🇦",
  },
  {
    code: "BB",
    unicode: "U+1F1E7 U+1F1E7",
    name: "Barbados",
    flag: "🇧🇧",
  },
  {
    code: "BD",
    unicode: "U+1F1E7 U+1F1E9",
    name: "Bangladesh",
    flag: "🇧🇩",
  },
  {
    code: "BE",
    unicode: "U+1F1E7 U+1F1EA",
    name: "Belgium",
    flag: "🇧🇪",
  },
  {
    code: "BF",
    unicode: "U+1F1E7 U+1F1EB",
    name: "Burkina Faso",
    flag: "🇧🇫",
  },
  {
    code: "BG",
    unicode: "U+1F1E7 U+1F1EC",
    name: "Bulgaria",
    flag: "🇧🇬",
  },
  {
    code: "BH",
    unicode: "U+1F1E7 U+1F1ED",
    name: "Bahrain",
    flag: "🇧🇭",
  },
  {
    code: "BI",
    unicode: "U+1F1E7 U+1F1EE",
    name: "Burundi",
    flag: "🇧🇮",
  },
  {
    code: "BJ",
    unicode: "U+1F1E7 U+1F1EF",
    name: "Benin",
    flag: "🇧🇯",
  },
  {
    code: "BL",
    unicode: "U+1F1E7 U+1F1F1",
    name: "St. Barthélemy",
    flag: "🇧🇱",
  },
  {
    code: "BM",
    unicode: "U+1F1E7 U+1F1F2",
    name: "Bermuda",
    flag: "🇧🇲",
  },
  {
    code: "BN",
    unicode: "U+1F1E7 U+1F1F3",
    name: "Brunei",
    flag: "🇧🇳",
  },
  {
    code: "BO",
    unicode: "U+1F1E7 U+1F1F4",
    name: "Bolivia",
    flag: "🇧🇴",
  },
  {
    code: "BQ",
    unicode: "U+1F1E7 U+1F1F6",
    name: "Caribbean Netherlands",
    flag: "🇧🇶",
  },
  {
    code: "BR",
    unicode: "U+1F1E7 U+1F1F7",
    name: "Brazil",
    flag: "🇧🇷",
  },
  {
    code: "BS",
    unicode: "U+1F1E7 U+1F1F8",
    name: "Bahamas",
    flag: "🇧🇸",
  },
  {
    code: "BT",
    unicode: "U+1F1E7 U+1F1F9",
    name: "Bhutan",
    flag: "🇧🇹",
  },
  {
    code: "BV",
    unicode: "U+1F1E7 U+1F1FB",
    name: "Bouvet Island",
    flag: "🇧🇻",
  },
  {
    code: "BW",
    unicode: "U+1F1E7 U+1F1FC",
    name: "Botswana",
    flag: "🇧🇼",
  },
  {
    code: "BY",
    unicode: "U+1F1E7 U+1F1FE",
    name: "Belarus",
    flag: "🇧🇾",
  },
  {
    code: "BZ",
    unicode: "U+1F1E7 U+1F1FF",
    name: "Belize",
    flag: "🇧🇿",
  },
  {
    code: "CA",
    unicode: "U+1F1E8 U+1F1E6",
    name: "Canada",
    flag: "🇨🇦",
  },
  {
    code: "CC",
    unicode: "U+1F1E8 U+1F1E8",
    name: "Cocos (Keeling) Islands",
    flag: "🇨🇨",
  },
  {
    code: "CD",
    unicode: "U+1F1E8 U+1F1E9",
    name: "Congo - Kinshasa",
    flag: "🇨🇩",
  },
  {
    code: "CF",
    unicode: "U+1F1E8 U+1F1EB",
    name: "Central African Republic",
    flag: "🇨🇫",
  },
  {
    code: "CG",
    unicode: "U+1F1E8 U+1F1EC",
    name: "Congo - Brazzaville",
    flag: "🇨🇬",
  },
  {
    code: "CH",
    unicode: "U+1F1E8 U+1F1ED",
    name: "Switzerland",
    flag: "🇨🇭",
  },
  {
    code: "CI",
    unicode: "U+1F1E8 U+1F1EE",
    name: "Côte d’Ivoire",
    flag: "🇨🇮",
  },
  {
    code: "CK",
    unicode: "U+1F1E8 U+1F1F0",
    name: "Cook Islands",
    flag: "🇨🇰",
  },
  {
    code: "CL",
    unicode: "U+1F1E8 U+1F1F1",
    name: "Chile",
    flag: "🇨🇱",
  },
  {
    code: "CM",
    unicode: "U+1F1E8 U+1F1F2",
    name: "Cameroon",
    flag: "🇨🇲",
  },
  {
    code: "CN",
    unicode: "U+1F1E8 U+1F1F3",
    name: "China",
    flag: "🇨🇳",
  },
  {
    code: "CO",
    unicode: "U+1F1E8 U+1F1F4",
    name: "Colombia",
    flag: "🇨🇴",
  },
  {
    code: "CP",
    unicode: "U+1F1E8 U+1F1F5",
    name: "Clipperton Island",
    flag: "🇨🇵",
  },
  {
    code: "CR",
    unicode: "U+1F1E8 U+1F1F7",
    name: "Costa Rica",
    flag: "🇨🇷",
  },
  {
    code: "CU",
    unicode: "U+1F1E8 U+1F1FA",
    name: "Cuba",
    flag: "🇨🇺",
  },
  {
    code: "CV",
    unicode: "U+1F1E8 U+1F1FB",
    name: "Cape Verde",
    flag: "🇨🇻",
  },
  {
    code: "CW",
    unicode: "U+1F1E8 U+1F1FC",
    name: "Curaçao",
    flag: "🇨🇼",
  },
  {
    code: "CX",
    unicode: "U+1F1E8 U+1F1FD",
    name: "Christmas Island",
    flag: "🇨🇽",
  },
  {
    code: "CY",
    unicode: "U+1F1E8 U+1F1FE",
    name: "Cyprus",
    flag: "🇨🇾",
  },
  {
    code: "CZ",
    unicode: "U+1F1E8 U+1F1FF",
    name: "Czechia",
    flag: "🇨🇿",
  },
  {
    code: "DE",
    unicode: "U+1F1E9 U+1F1EA",
    name: "Germany",
    flag: "🇩🇪",
  },
  {
    code: "DG",
    unicode: "U+1F1E9 U+1F1EC",
    name: "Diego Garcia",
    flag: "🇩🇬",
  },
  {
    code: "DJ",
    unicode: "U+1F1E9 U+1F1EF",
    name: "Djibouti",
    flag: "🇩🇯",
  },
  {
    code: "DK",
    unicode: "U+1F1E9 U+1F1F0",
    name: "Denmark",
    flag: "🇩🇰",
  },
  {
    code: "DM",
    unicode: "U+1F1E9 U+1F1F2",
    name: "Dominica",
    flag: "🇩🇲",
  },
  {
    code: "DO",
    unicode: "U+1F1E9 U+1F1F4",
    name: "Dominican Republic",
    flag: "🇩🇴",
  },
  {
    code: "DZ",
    unicode: "U+1F1E9 U+1F1FF",
    name: "Algeria",
    flag: "🇩🇿",
  },
  {
    code: "EA",
    unicode: "U+1F1EA U+1F1E6",
    name: "Ceuta & Melilla",
    flag: "🇪🇦",
  },
  {
    code: "EC",
    unicode: "U+1F1EA U+1F1E8",
    name: "Ecuador",
    flag: "🇪🇨",
  },
  {
    code: "EE",
    unicode: "U+1F1EA U+1F1EA",
    name: "Estonia",
    flag: "🇪🇪",
  },
  {
    code: "EG",
    unicode: "U+1F1EA U+1F1EC",
    name: "Egypt",
    flag: "🇪🇬",
  },
  {
    code: "EH",
    unicode: "U+1F1EA U+1F1ED",
    name: "Western Sahara",
    flag: "🇪🇭",
  },
  {
    code: "ER",
    unicode: "U+1F1EA U+1F1F7",
    name: "Eritrea",
    flag: "🇪🇷",
  },
  {
    code: "ES",
    unicode: "U+1F1EA U+1F1F8",
    name: "Spain",
    flag: "🇪🇸",
  },
  {
    code: "ET",
    unicode: "U+1F1EA U+1F1F9",
    name: "Ethiopia",
    flag: "🇪🇹",
  },
  {
    code: "EU",
    unicode: "U+1F1EA U+1F1FA",
    name: "European Union",
    flag: "🇪🇺",
  },
  {
    code: "FI",
    unicode: "U+1F1EB U+1F1EE",
    name: "Finland",
    flag: "🇫🇮",
  },
  {
    code: "FJ",
    unicode: "U+1F1EB U+1F1EF",
    name: "Fiji",
    flag: "🇫🇯",
  },
  {
    code: "FK",
    unicode: "U+1F1EB U+1F1F0",
    name: "Falkland Islands",
    flag: "🇫🇰",
  },
  {
    code: "FM",
    unicode: "U+1F1EB U+1F1F2",
    name: "Micronesia",
    flag: "🇫🇲",
  },
  {
    code: "FO",
    unicode: "U+1F1EB U+1F1F4",
    name: "Faroe Islands",
    flag: "🇫🇴",
  },
  {
    code: "FR",
    unicode: "U+1F1EB U+1F1F7",
    name: "France",
    flag: "🇫🇷",
  },
  {
    code: "GA",
    unicode: "U+1F1EC U+1F1E6",
    name: "Gabon",
    flag: "🇬🇦",
  },
  {
    code: "GB",
    unicode: "U+1F1EC U+1F1E7",
    name: "United Kingdom",
    flag: "🇬🇧",
  },
  {
    code: "GD",
    unicode: "U+1F1EC U+1F1E9",
    name: "Grenada",
    flag: "🇬🇩",
  },
  {
    code: "GE",
    unicode: "U+1F1EC U+1F1EA",
    name: "Georgia",
    flag: "🇬🇪",
  },
  {
    code: "GF",
    unicode: "U+1F1EC U+1F1EB",
    name: "French Guiana",
    flag: "🇬🇫",
  },
  {
    code: "GG",
    unicode: "U+1F1EC U+1F1EC",
    name: "Guernsey",
    flag: "🇬🇬",
  },
  {
    code: "GH",
    unicode: "U+1F1EC U+1F1ED",
    name: "Ghana",
    flag: "🇬🇭",
  },
  {
    code: "GI",
    unicode: "U+1F1EC U+1F1EE",
    name: "Gibraltar",
    flag: "🇬🇮",
  },
  {
    code: "GL",
    unicode: "U+1F1EC U+1F1F1",
    name: "Greenland",
    flag: "🇬🇱",
  },
  {
    code: "GM",
    unicode: "U+1F1EC U+1F1F2",
    name: "Gambia",
    flag: "🇬🇲",
  },
  {
    code: "GN",
    unicode: "U+1F1EC U+1F1F3",
    name: "Guinea",
    flag: "🇬🇳",
  },
  {
    code: "GP",
    unicode: "U+1F1EC U+1F1F5",
    name: "Guadeloupe",
    flag: "🇬🇵",
  },
  {
    code: "GQ",
    unicode: "U+1F1EC U+1F1F6",
    name: "Equatorial Guinea",
    flag: "🇬🇶",
  },
  {
    code: "GR",
    unicode: "U+1F1EC U+1F1F7",
    name: "Greece",
    flag: "🇬🇷",
  },
  {
    code: "GS",
    unicode: "U+1F1EC U+1F1F8",
    name: "South Georgia & South Sandwich Islands",
    flag: "🇬🇸",
  },
  {
    code: "GT",
    unicode: "U+1F1EC U+1F1F9",
    name: "Guatemala",
    flag: "🇬🇹",
  },
  {
    code: "GU",
    unicode: "U+1F1EC U+1F1FA",
    name: "Guam",
    flag: "🇬🇺",
  },
  {
    code: "GW",
    unicode: "U+1F1EC U+1F1FC",
    name: "Guinea-Bissau",
    flag: "🇬🇼",
  },
  {
    code: "GY",
    unicode: "U+1F1EC U+1F1FE",
    name: "Guyana",
    flag: "🇬🇾",
  },
  {
    code: "HK",
    unicode: "U+1F1ED U+1F1F0",
    name: "Hong Kong SAR China",
    flag: "🇭🇰",
  },
  {
    code: "HM",
    unicode: "U+1F1ED U+1F1F2",
    name: "Heard & McDonald Islands",
    flag: "🇭🇲",
  },
  {
    code: "HN",
    unicode: "U+1F1ED U+1F1F3",
    name: "Honduras",
    flag: "🇭🇳",
  },
  {
    code: "HR",
    unicode: "U+1F1ED U+1F1F7",
    name: "Croatia",
    flag: "🇭🇷",
  },
  {
    code: "HT",
    unicode: "U+1F1ED U+1F1F9",
    name: "Haiti",
    flag: "🇭🇹",
  },
  {
    code: "HU",
    unicode: "U+1F1ED U+1F1FA",
    name: "Hungary",
    flag: "🇭🇺",
  },
  {
    code: "IC",
    unicode: "U+1F1EE U+1F1E8",
    name: "Canary Islands",
    flag: "🇮🇨",
  },
  {
    code: "ID",
    unicode: "U+1F1EE U+1F1E9",
    name: "Indonesia",
    flag: "🇮🇩",
  },
  {
    code: "IE",
    unicode: "U+1F1EE U+1F1EA",
    name: "Ireland",
    flag: "🇮🇪",
  },
  {
    code: "IL",
    unicode: "U+1F1EE U+1F1F1",
    name: "Israel",
    flag: "🇮🇱",
  },
  {
    code: "IM",
    unicode: "U+1F1EE U+1F1F2",
    name: "Isle of Man",
    flag: "🇮🇲",
  },
  {
    code: "IN",
    unicode: "U+1F1EE U+1F1F3",
    name: "India",
    flag: "🇮🇳",
  },
  {
    code: "IO",
    unicode: "U+1F1EE U+1F1F4",
    name: "British Indian Ocean Territory",
    flag: "🇮🇴",
  },
  {
    code: "IQ",
    unicode: "U+1F1EE U+1F1F6",
    name: "Iraq",
    flag: "🇮🇶",
  },
  {
    code: "IR",
    unicode: "U+1F1EE U+1F1F7",
    name: "Iran",
    flag: "🇮🇷",
  },
  {
    code: "IS",
    unicode: "U+1F1EE U+1F1F8",
    name: "Iceland",
    flag: "🇮🇸",
  },
  {
    code: "IT",
    unicode: "U+1F1EE U+1F1F9",
    name: "Italy",
    flag: "🇮🇹",
  },
  {
    code: "JE",
    unicode: "U+1F1EF U+1F1EA",
    name: "Jersey",
    flag: "🇯🇪",
  },
  {
    code: "JM",
    unicode: "U+1F1EF U+1F1F2",
    name: "Jamaica",
    flag: "🇯🇲",
  },
  {
    code: "JO",
    unicode: "U+1F1EF U+1F1F4",
    name: "Jordan",
    flag: "🇯🇴",
  },
  {
    code: "JP",
    unicode: "U+1F1EF U+1F1F5",
    name: "Japan",
    flag: "🇯🇵",
  },
  {
    code: "KE",
    unicode: "U+1F1F0 U+1F1EA",
    name: "Kenya",
    flag: "🇰🇪",
  },
  {
    code: "KG",
    unicode: "U+1F1F0 U+1F1EC",
    name: "Kyrgyzstan",
    flag: "🇰🇬",
  },
  {
    code: "KH",
    unicode: "U+1F1F0 U+1F1ED",
    name: "Cambodia",
    flag: "🇰🇭",
  },
  {
    code: "KI",
    unicode: "U+1F1F0 U+1F1EE",
    name: "Kiribati",
    flag: "🇰🇮",
  },
  {
    code: "KM",
    unicode: "U+1F1F0 U+1F1F2",
    name: "Comoros",
    flag: "🇰🇲",
  },
  {
    code: "KN",
    unicode: "U+1F1F0 U+1F1F3",
    name: "St. Kitts & Nevis",
    flag: "🇰🇳",
  },
  {
    code: "KP",
    unicode: "U+1F1F0 U+1F1F5",
    name: "North Korea",
    flag: "🇰🇵",
  },
  {
    code: "KR",
    unicode: "U+1F1F0 U+1F1F7",
    name: "South Korea",
    flag: "🇰🇷",
  },
  {
    code: "KW",
    unicode: "U+1F1F0 U+1F1FC",
    name: "Kuwait",
    flag: "🇰🇼",
  },
  {
    code: "KY",
    unicode: "U+1F1F0 U+1F1FE",
    name: "Cayman Islands",
    flag: "🇰🇾",
  },
  {
    code: "KZ",
    unicode: "U+1F1F0 U+1F1FF",
    name: "Kazakhstan",
    flag: "🇰🇿",
  },
  {
    code: "LA",
    unicode: "U+1F1F1 U+1F1E6",
    name: "Laos",
    flag: "🇱🇦",
  },
  {
    code: "LB",
    unicode: "U+1F1F1 U+1F1E7",
    name: "Lebanon",
    flag: "🇱🇧",
  },
  {
    code: "LC",
    unicode: "U+1F1F1 U+1F1E8",
    name: "St. Lucia",
    flag: "🇱🇨",
  },
  {
    code: "LI",
    unicode: "U+1F1F1 U+1F1EE",
    name: "Liechtenstein",
    flag: "🇱🇮",
  },
  {
    code: "LK",
    unicode: "U+1F1F1 U+1F1F0",
    name: "Sri Lanka",
    flag: "🇱🇰",
  },
  {
    code: "LR",
    unicode: "U+1F1F1 U+1F1F7",
    name: "Liberia",
    flag: "🇱🇷",
  },
  {
    code: "LS",
    unicode: "U+1F1F1 U+1F1F8",
    name: "Lesotho",
    flag: "🇱🇸",
  },
  {
    code: "LT",
    unicode: "U+1F1F1 U+1F1F9",
    name: "Lithuania",
    flag: "🇱🇹",
  },
  {
    code: "LU",
    unicode: "U+1F1F1 U+1F1FA",
    name: "Luxembourg",
    flag: "🇱🇺",
  },
  {
    code: "LV",
    unicode: "U+1F1F1 U+1F1FB",
    name: "Latvia",
    flag: "🇱🇻",
  },
  {
    code: "LY",
    unicode: "U+1F1F1 U+1F1FE",
    name: "Libya",
    flag: "🇱🇾",
  },
  {
    code: "MA",
    unicode: "U+1F1F2 U+1F1E6",
    name: "Morocco",
    flag: "🇲🇦",
  },
  {
    code: "MC",
    unicode: "U+1F1F2 U+1F1E8",
    name: "Monaco",
    flag: "🇲🇨",
  },
  {
    code: "MD",
    unicode: "U+1F1F2 U+1F1E9",
    name: "Moldova",
    flag: "🇲🇩",
  },
  {
    code: "ME",
    unicode: "U+1F1F2 U+1F1EA",
    name: "Montenegro",
    flag: "🇲🇪",
  },
  {
    code: "MF",
    unicode: "U+1F1F2 U+1F1EB",
    name: "St. Martin",
    flag: "🇲🇫",
  },
  {
    code: "MG",
    unicode: "U+1F1F2 U+1F1EC",
    name: "Madagascar",
    flag: "🇲🇬",
  },
  {
    code: "MH",
    unicode: "U+1F1F2 U+1F1ED",
    name: "Marshall Islands",
    flag: "🇲🇭",
  },
  {
    code: "MK",
    unicode: "U+1F1F2 U+1F1F0",
    name: "Macedonia",
    flag: "🇲🇰",
  },
  {
    code: "ML",
    unicode: "U+1F1F2 U+1F1F1",
    name: "Mali",
    flag: "🇲🇱",
  },
  {
    code: "MM",
    unicode: "U+1F1F2 U+1F1F2",
    name: "Myanmar (Burma)",
    flag: "🇲🇲",
  },
  {
    code: "MN",
    unicode: "U+1F1F2 U+1F1F3",
    name: "Mongolia",
    flag: "🇲🇳",
  },
  {
    code: "MO",
    unicode: "U+1F1F2 U+1F1F4",
    name: "Macau SAR China",
    flag: "🇲🇴",
  },
  {
    code: "MP",
    unicode: "U+1F1F2 U+1F1F5",
    name: "Northern Mariana Islands",
    flag: "🇲🇵",
  },
  {
    code: "MQ",
    unicode: "U+1F1F2 U+1F1F6",
    name: "Martinique",
    flag: "🇲🇶",
  },
  {
    code: "MR",
    unicode: "U+1F1F2 U+1F1F7",
    name: "Mauritania",
    flag: "🇲🇷",
  },
  {
    code: "MS",
    unicode: "U+1F1F2 U+1F1F8",
    name: "Montserrat",
    flag: "🇲🇸",
  },
  {
    code: "MT",
    unicode: "U+1F1F2 U+1F1F9",
    name: "Malta",
    flag: "🇲🇹",
  },
  {
    code: "MU",
    unicode: "U+1F1F2 U+1F1FA",
    name: "Mauritius",
    flag: "🇲🇺",
  },
  {
    code: "MV",
    unicode: "U+1F1F2 U+1F1FB",
    name: "Maldives",
    flag: "🇲🇻",
  },
  {
    code: "MW",
    unicode: "U+1F1F2 U+1F1FC",
    name: "Malawi",
    flag: "🇲🇼",
  },
  {
    code: "MX",
    unicode: "U+1F1F2 U+1F1FD",
    name: "Mexico",
    flag: "🇲🇽",
  },
  {
    code: "MY",
    unicode: "U+1F1F2 U+1F1FE",
    name: "Malaysia",
    flag: "🇲🇾",
  },
  {
    code: "MZ",
    unicode: "U+1F1F2 U+1F1FF",
    name: "Mozambique",
    flag: "🇲🇿",
  },
  {
    code: "NA",
    unicode: "U+1F1F3 U+1F1E6",
    name: "Namibia",
    flag: "🇳🇦",
  },
  {
    code: "NC",
    unicode: "U+1F1F3 U+1F1E8",
    name: "New Caledonia",
    flag: "🇳🇨",
  },
  {
    code: "NE",
    unicode: "U+1F1F3 U+1F1EA",
    name: "Niger",
    flag: "🇳🇪",
  },
  {
    code: "NF",
    unicode: "U+1F1F3 U+1F1EB",
    name: "Norfolk Island",
    flag: "🇳🇫",
  },
  {
    code: "NG",
    unicode: "U+1F1F3 U+1F1EC",
    name: "Nigeria",
    flag: "🇳🇬",
  },
  {
    code: "NI",
    unicode: "U+1F1F3 U+1F1EE",
    name: "Nicaragua",
    flag: "🇳🇮",
  },
  {
    code: "NL",
    unicode: "U+1F1F3 U+1F1F1",
    name: "Netherlands",
    flag: "🇳🇱",
  },
  {
    code: "NO",
    unicode: "U+1F1F3 U+1F1F4",
    name: "Norway",
    flag: "🇳🇴",
  },
  {
    code: "NP",
    unicode: "U+1F1F3 U+1F1F5",
    name: "Nepal",
    flag: "🇳🇵",
  },
  {
    code: "NR",
    unicode: "U+1F1F3 U+1F1F7",
    name: "Nauru",
    flag: "🇳🇷",
  },
  {
    code: "NU",
    unicode: "U+1F1F3 U+1F1FA",
    name: "Niue",
    flag: "🇳🇺",
  },
  {
    code: "NZ",
    unicode: "U+1F1F3 U+1F1FF",
    name: "New Zealand",
    flag: "🇳🇿",
  },
  {
    code: "OM",
    unicode: "U+1F1F4 U+1F1F2",
    name: "Oman",
    flag: "🇴🇲",
  },
  {
    code: "PA",
    unicode: "U+1F1F5 U+1F1E6",
    name: "Panama",
    flag: "🇵🇦",
  },
  {
    code: "PE",
    unicode: "U+1F1F5 U+1F1EA",
    name: "Peru",
    flag: "🇵🇪",
  },
  {
    code: "PF",
    unicode: "U+1F1F5 U+1F1EB",
    name: "French Polynesia",
    flag: "🇵🇫",
  },
  {
    code: "PG",
    unicode: "U+1F1F5 U+1F1EC",
    name: "Papua New Guinea",
    flag: "🇵🇬",
  },
  {
    code: "PH",
    unicode: "U+1F1F5 U+1F1ED",
    name: "Philippines",
    flag: "🇵🇭",
  },
  {
    code: "PK",
    unicode: "U+1F1F5 U+1F1F0",
    name: "Pakistan",
    flag: "🇵🇰",
  },
  {
    code: "PL",
    unicode: "U+1F1F5 U+1F1F1",
    name: "Poland",
    flag: "🇵🇱",
  },
  {
    code: "PM",
    unicode: "U+1F1F5 U+1F1F2",
    name: "St. Pierre & Miquelon",
    flag: "🇵🇲",
  },
  {
    code: "PN",
    unicode: "U+1F1F5 U+1F1F3",
    name: "Pitcairn Islands",
    flag: "🇵🇳",
  },
  {
    code: "PR",
    unicode: "U+1F1F5 U+1F1F7",
    name: "Puerto Rico",
    flag: "🇵🇷",
  },
  {
    code: "PS",
    unicode: "U+1F1F5 U+1F1F8",
    name: "Palestinian Territories",
    flag: "🇵🇸",
  },
  {
    code: "PT",
    unicode: "U+1F1F5 U+1F1F9",
    name: "Portugal",
    flag: "🇵🇹",
  },
  {
    code: "PW",
    unicode: "U+1F1F5 U+1F1FC",
    name: "Palau",
    flag: "🇵🇼",
  },
  {
    code: "PY",
    unicode: "U+1F1F5 U+1F1FE",
    name: "Paraguay",
    flag: "🇵🇾",
  },
  {
    code: "QA",
    unicode: "U+1F1F6 U+1F1E6",
    name: "Qatar",
    flag: "🇶🇦",
  },
  {
    code: "RE",
    unicode: "U+1F1F7 U+1F1EA",
    name: "Réunion",
    flag: "🇷🇪",
  },
  {
    code: "RO",
    unicode: "U+1F1F7 U+1F1F4",
    name: "Romania",
    flag: "🇷🇴",
  },
  {
    code: "RS",
    unicode: "U+1F1F7 U+1F1F8",
    name: "Serbia",
    flag: "🇷🇸",
  },
  {
    code: "RU",
    unicode: "U+1F1F7 U+1F1FA",
    name: "Russia",
    flag: "🇷🇺",
  },
  {
    code: "RW",
    unicode: "U+1F1F7 U+1F1FC",
    name: "Rwanda",
    flag: "🇷🇼",
  },
  {
    code: "SA",
    unicode: "U+1F1F8 U+1F1E6",
    name: "Saudi Arabia",
    flag: "🇸🇦",
  },
  {
    code: "SB",
    unicode: "U+1F1F8 U+1F1E7",
    name: "Solomon Islands",
    flag: "🇸🇧",
  },
  {
    code: "SC",
    unicode: "U+1F1F8 U+1F1E8",
    name: "Seychelles",
    flag: "🇸🇨",
  },
  {
    code: "SD",
    unicode: "U+1F1F8 U+1F1E9",
    name: "Sudan",
    flag: "🇸🇩",
  },
  {
    code: "SE",
    unicode: "U+1F1F8 U+1F1EA",
    name: "Sweden",
    flag: "🇸🇪",
  },
  {
    code: "SG",
    unicode: "U+1F1F8 U+1F1EC",
    name: "Singapore",
    flag: "🇸🇬",
  },
  {
    code: "SH",
    unicode: "U+1F1F8 U+1F1ED",
    name: "St. Helena",
    flag: "🇸🇭",
  },
  {
    code: "SI",
    unicode: "U+1F1F8 U+1F1EE",
    name: "Slovenia",
    flag: "🇸🇮",
  },
  {
    code: "SJ",
    unicode: "U+1F1F8 U+1F1EF",
    name: "Svalbard & Jan Mayen",
    flag: "🇸🇯",
  },
  {
    code: "SK",
    unicode: "U+1F1F8 U+1F1F0",
    name: "Slovakia",
    flag: "🇸🇰",
  },
  {
    code: "SL",
    unicode: "U+1F1F8 U+1F1F1",
    name: "Sierra Leone",
    flag: "🇸🇱",
  },
  {
    code: "SM",
    unicode: "U+1F1F8 U+1F1F2",
    name: "San Marino",
    flag: "🇸🇲",
  },
  {
    code: "SN",
    unicode: "U+1F1F8 U+1F1F3",
    name: "Senegal",
    flag: "🇸🇳",
  },
  {
    code: "SO",
    unicode: "U+1F1F8 U+1F1F4",
    name: "Somalia",
    flag: "🇸🇴",
  },
  {
    code: "SR",
    unicode: "U+1F1F8 U+1F1F7",
    name: "Suriname",
    flag: "🇸🇷",
  },
  {
    code: "SS",
    unicode: "U+1F1F8 U+1F1F8",
    name: "South Sudan",
    flag: "🇸🇸",
  },
  {
    code: "ST",
    unicode: "U+1F1F8 U+1F1F9",
    name: "São Tomé & Príncipe",
    flag: "🇸🇹",
  },
  {
    code: "SV",
    unicode: "U+1F1F8 U+1F1FB",
    name: "El Salvador",
    flag: "🇸🇻",
  },
  {
    code: "SX",
    unicode: "U+1F1F8 U+1F1FD",
    name: "Sint Maarten",
    flag: "🇸🇽",
  },
  {
    code: "SY",
    unicode: "U+1F1F8 U+1F1FE",
    name: "Syria",
    flag: "🇸🇾",
  },
  {
    code: "SZ",
    unicode: "U+1F1F8 U+1F1FF",
    name: "Swaziland",
    flag: "🇸🇿",
  },
  {
    code: "TA",
    unicode: "U+1F1F9 U+1F1E6",
    name: "Tristan da Cunha",
    flag: "🇹🇦",
  },
  {
    code: "TC",
    unicode: "U+1F1F9 U+1F1E8",
    name: "Turks & Caicos Islands",
    flag: "🇹🇨",
  },
  {
    code: "TD",
    unicode: "U+1F1F9 U+1F1E9",
    name: "Chad",
    flag: "🇹🇩",
  },
  {
    code: "TF",
    unicode: "U+1F1F9 U+1F1EB",
    name: "French Southern Territories",
    flag: "🇹🇫",
  },
  {
    code: "TG",
    unicode: "U+1F1F9 U+1F1EC",
    name: "Togo",
    flag: "🇹🇬",
  },
  {
    code: "TH",
    unicode: "U+1F1F9 U+1F1ED",
    name: "Thailand",
    flag: "🇹🇭",
  },
  {
    code: "TJ",
    unicode: "U+1F1F9 U+1F1EF",
    name: "Tajikistan",
    flag: "🇹🇯",
  },
  {
    code: "TK",
    unicode: "U+1F1F9 U+1F1F0",
    name: "Tokelau",
    flag: "🇹🇰",
  },
  {
    code: "TL",
    unicode: "U+1F1F9 U+1F1F1",
    name: "Timor-Leste",
    flag: "🇹🇱",
  },
  {
    code: "TM",
    unicode: "U+1F1F9 U+1F1F2",
    name: "Turkmenistan",
    flag: "🇹🇲",
  },
  {
    code: "TN",
    unicode: "U+1F1F9 U+1F1F3",
    name: "Tunisia",
    flag: "🇹🇳",
  },
  {
    code: "TO",
    unicode: "U+1F1F9 U+1F1F4",
    name: "Tonga",
    flag: "🇹🇴",
  },
  {
    code: "TR",
    unicode: "U+1F1F9 U+1F1F7",
    name: "Turkey",
    flag: "🇹🇷",
  },
  {
    code: "TT",
    unicode: "U+1F1F9 U+1F1F9",
    name: "Trinidad & Tobago",
    flag: "🇹🇹",
  },
  {
    code: "TV",
    unicode: "U+1F1F9 U+1F1FB",
    name: "Tuvalu",
    flag: "🇹🇻",
  },
  {
    code: "TW",
    unicode: "U+1F1F9 U+1F1FC",
    name: "Taiwan",
    flag: "🇹🇼",
  },
  {
    code: "TZ",
    unicode: "U+1F1F9 U+1F1FF",
    name: "Tanzania",
    flag: "🇹🇿",
  },
  {
    code: "UA",
    unicode: "U+1F1FA U+1F1E6",
    name: "Ukraine",
    flag: "🇺🇦",
  },
  {
    code: "UG",
    unicode: "U+1F1FA U+1F1EC",
    name: "Uganda",
    flag: "🇺🇬",
  },
  {
    code: "UM",
    unicode: "U+1F1FA U+1F1F2",
    name: "U.S. Outlying Islands",
    flag: "🇺🇲",
  },
  {
    code: "UN",
    unicode: "U+1F1FA U+1F1F3",
    name: "United Nations",
    flag: "🇺🇳",
  },
  {
    code: "US",
    unicode: "U+1F1FA U+1F1F8",
    name: "United States",
    flag: "🇺🇸",
  },
  {
    code: "UY",
    unicode: "U+1F1FA U+1F1FE",
    name: "Uruguay",
    flag: "🇺🇾",
  },
  {
    code: "UZ",
    unicode: "U+1F1FA U+1F1FF",
    name: "Uzbekistan",
    flag: "🇺🇿",
  },
  {
    code: "VA",
    unicode: "U+1F1FB U+1F1E6",
    name: "Vatican City",
    flag: "🇻🇦",
  },
  {
    code: "VC",
    unicode: "U+1F1FB U+1F1E8",
    name: "St. Vincent & Grenadines",
    flag: "🇻🇨",
  },
  {
    code: "VE",
    unicode: "U+1F1FB U+1F1EA",
    name: "Venezuela",
    flag: "🇻🇪",
  },
  {
    code: "VG",
    unicode: "U+1F1FB U+1F1EC",
    name: "British Virgin Islands",
    flag: "🇻🇬",
  },
  {
    code: "VI",
    unicode: "U+1F1FB U+1F1EE",
    name: "U.S. Virgin Islands",
    flag: "🇻🇮",
  },
  {
    code: "VN",
    unicode: "U+1F1FB U+1F1F3",
    name: "Vietnam",
    flag: "🇻🇳",
  },
  {
    code: "VU",
    unicode: "U+1F1FB U+1F1FA",
    name: "Vanuatu",
    flag: "🇻🇺",
  },
  {
    code: "WF",
    unicode: "U+1F1FC U+1F1EB",
    name: "Wallis & Futuna",
    flag: "🇼🇫",
  },
  {
    code: "WS",
    unicode: "U+1F1FC U+1F1F8",
    name: "Samoa",
    flag: "🇼🇸",
  },
  {
    code: "XK",
    unicode: "U+1F1FD U+1F1F0",
    name: "Kosovo",
    flag: "🇽🇰",
  },
  {
    code: "YE",
    unicode: "U+1F1FE U+1F1EA",
    name: "Yemen",
    flag: "🇾🇪",
  },
  {
    code: "YT",
    unicode: "U+1F1FE U+1F1F9",
    name: "Mayotte",
    flag: "🇾🇹",
  },
  {
    code: "ZA",
    unicode: "U+1F1FF U+1F1E6",
    name: "South Africa",
    flag: "🇿🇦",
  },
  {
    code: "ZM",
    unicode: "U+1F1FF U+1F1F2",
    name: "Zambia",
    flag: "🇿🇲",
  },
  {
    code: "ZW",
    unicode: "U+1F1FF U+1F1FC",
    name: "Zimbabwe",
    flag: "🇿🇼",
  },
];

export default flags;
